<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-SecureLoginApp1-c0eb2a5e-a1f8-4e5e-b320-ab6ae30f3184</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.29" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.29" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.29" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.29" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.29" />
  </ItemGroup>

</Project>
